version: '3.8'

services:
  replit_app:
    build: .
    container_name: ${APP_NAME}       
    environment:
      NODE_ENV: production  
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
      PORT: 5000
    networks:
      - nginx_network
    expose:
      - "5000"
    restart: unless-stopped
networks:
  nginx_network:
    external: true

